### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by andrey-star** [Life-Science-Project/LifeScience#22]
- [x] Rename `exceptions` package to `exception`
- [x] Replace uppercase `ID` with `Id` in field and method names
- [x] Make API endpoints available at plural versions of entities (`/articles`, `/sections`)
- [x] Move all `Method` related stuff to `method` package (`MethodVersion`, `MethodReview`)
- [x] `Section` -> `Category`, `Method` -> `Article`, `Container` -> `Section`, `Article` -> `Content`

**Comment by avpotapov00** [comment]
Make all controller and service `add` methods return the result - будем делать по необходимости

**Comment by avpotapov00** [comment]
Make more use of `MethodController`, remove unnecessary endpoints (`/review`, `/versions`) - мне кажется там потом будет побольше логики, поэтому пока давайте оставим так
