### ISSUE TITLE
Fix SQL error in addSection

### ISSUE THREAD

**Issue by andrey-star** [Life-Science-Project/LifeScience#25]
When `addSection` is called with `parentId` of a non-existing Section, the server throws an SQL error instead of `SectionNotFound`
Should be fixed in `addSection` in `SectionServiceImpl`

https://github.com/Life-Science-Project/LifeScience/blob/958b6d361931f3c6e6416292ce050d887b170fbd/backend/src/main/kotlin/com/jetbrains/life_science/section/service/SectionServiceImpl.kt#L16-L21

**Comment by avpotapov00** [comment]
Done
